# Configuration for DIME Interfaces.
# https://dime-xai.github.io/dime-configs

# Configurations that applies to both DIME CLI and Server
# If no config is provided following are the default configurations that DIME uses.
# Please adjust them accordingly.
# See https://dime-xai.github.io/dime-configs for more information.
dime_base_configs:
  - languages:
      - 'en'
      - 'si'
  - data_path: ./data/
  - models_path: ./models/
    model_name: latest
  - model_type: diet
    rasa_version: 2.8.8
  - model_mode: local
  - url_endpoint: http://localhost:5005
  - data_instance:
      - "SLIIT එකේ තියෙන උපාධි මොනවද?"
#      - "First class degree එකක් ගන්න GPA එක කොච්චර ඕනෙද"
  - ranking_length: 10
  - ngrams: False
    min_ngrams: 1
    max_ngrams: 2
  - case_sensitive: True
  - metric: confidence

# Configurations that applies to DIME Server
# If no config is provided following are the default configurations that DIME Server uses.
# Please adjust them accordingly.
# See https://dime-xai.github.io/dime-configs for more information.
dime_server_configs:
  - host: localhost
  - port: 6066
  - output_mode: dual

# Configurations that applies to DIME CLI
# If no config is provided following are the default configurations that DIME CLI uses.
# Please adjust them accordingly.
# See https://dime-xai.github.io/dime-configs for more information.
dime_cli_configs:
  - output_mode: dual
